from BinaryTree import Node
from BinaryTree import BinaryTree
# tester node
my_node = Node('hello')
# print(my_node)
my_BST = BinaryTree()
my_BST.insert(10)
# print(my_BST.root)
my_BST.insert(12)
my_BST.insert(8)
# print(my_BST.root.right)
# my_BST.print()
my_BST.insert(15)
my_BST.insert(9)
my_BST.insert(3)
my_BST.insert(1)
my_BST.insert(87)
# print(my_BST.search(87))
print(my_BST.print())
# print('max val should be 87', my_BST.get_max())
# print('min val should be 1', my_BST.get_min())
# print('Size should be 8:', my_BST.size())
print('Height should be 5:', my_BST.height())